NETWORK_ID = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
CORE_MAJOR_VERSION = 0
FIRST_EPOCH_START_TIMESTAMP = 1749254009203

[NETWORK_PARAMETERS]
VALIDATOR_STAKE = "50000000000000000000000"
MINIMAL_STAKE_PER_ENTITY = "20000000000000000000"
QUORUM_SIZE = 127
EPOCH_TIME = 120000
LEADERSHIP_TIMEFRAME = 120000
BLOCK_TIME = 1000
MAX_BLOCK_SIZE_IN_BYTES = 12288000
TXS_LIMIT_PER_BLOCK = 30000

[POOLS."9GQ46rqY238rk2neSwgidap9ww5zbAN4dyqyC7j5ZnBK"]
PERCENTAGE = 50
PERCEPTION_SCORE = 0
TOTAL_STAKED = "55000000000000000000000"
POOLURL = "localhost:7332"

[POOLS."9GQ46rqY238rk2neSwgidap9ww5zbAN4dyqyC7j5ZnBK".STAKERS."9GQ46rqY238rk2neSwgidap9ww5zbAN4dyqyC7j5ZnBK"]
STAKE = "1000000000000000000000"

[STATE."9GQ46rqY238rk2neSwgidap9ww5zbAN4dyqyC7j5ZnBK"]
TYPE = "eoa"
BALANCE = 20000000
NONCE = 0